[workspace]
authors = ["tkt-gemini <tkt310505@gmail.com>"]
channels = ["conda-forge"]
name = "project-2"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
pynvim = ">=0.6.0,<0.7"
pandas = "*"
imbalanced-learn = "*"
ipykernel = ">=7.1.0,<8"
numpy = "*"
nltk = "*"
matplotlib = "*"
wordcloud = "*"
emoji = "*"
empath = "*"
spacy = "*"
seaborn = "*"
scikit-learn = "*"
spacy-model-en_core_web_sm = "*"
streamlit = ">=1.30.0"
textstat = "*"
jupyter_client = ">=8.8.0,<9"
joblib = "*"

[pypi-dependencies]
contractions = "*"